# Generated by Django 4.2.8 on 2024-01-31 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='Done',
            new_name='completed',
        ),
    ]
